### ISSUE TITLE
Onjuiste gebruikersnaam

### ISSUE THREAD

**Issue by Argetan** [deltaproject/Delta#15]
Rond 16:45 vandaag begon `magister.js` een error te gooien "invalid username". Uiteraard waren mijn gegevens gewoon goed ingevuld. Het onderliggende probleem is dat de authenticatiecode is veranderd. 

Oplossing:
`npm i magister.js@2.0.0-alpha.8`

Het lijkt mij echter beter om een script te schrijven dat de code direct ophaald van Github. Ik zal dit waarschijnlijk later vandaag of morgen doen.

**Comment by keesvv** [comment]
Als ik straks klaar ben ga ik er even achteraan, er bestaat al een script die dynamisch de authenticatiecode ophaalt. De visuele bugs fix ik later wel maar dit heeft een hoge prioriteit, aangezien er nu geen gebruikers meer kunnen inloggen.
