### ISSUE TITLE
Prestaties en laatste cijfers worden niet weergegeven

### ISSUE THREAD

**Issue by Argetan** [deltaproject/Delta#16]
Het lijkt eropt dat prestaties en laatste cijfers niet willen laden ook al zijn de cijfers wel geladen. Het kan zijn dat dit alleen een visuele bug is.

**Comment by keesvv** [comment]
Dat is inderdaad een visuele bug, echter, het werkte laatst nog wel. Als er geen cijfers beschikbaar waren zou er bij prestaties een melding komen te staan dat prestaties pas getoond kunnen worden als er cijfers zijn gehaald. Daar ga ik ook even naar kijken.

**Comment by Argetan** [comment]
Na verder onderzoek ben ik erachter gekomen dat deze bug niet visueel is. Het probleem zit hem in de functies die de cijfers filteren en selecteren. Ik zal zo een PR maken die deze problemen verhelpt.

Het is echter zo dat de cijfers nog steeds niet helemaal correct worden verwerkt. Zo staat mijn gemiddelde over alle vakken bij de laatst behaalde cijfers, de kolom met het aantal onvoldoendes (die tevens onvoldoende is omdat ik 0 onvoldoendes heb) en de cijfers staan in een willekeurige volgorde in plaats van gesorteerd op datum.

Er zal wat meer onderzoek nodig zijn om erachter te komen hoe de cijfers objecten precies in elkaar zitten en hoe we deze kunnen verwerken. Aangezien dit redelijk wat werk zal zijn stel ik voor dit wellicht uit te stellen totdat we weten hoe we de UI precies willen hebben (#20) en dan kijken welke functies we daarvoor nodig hebben.

**Comment by Argetan** [comment]
Als ik naar mijn eigen cijfers kijk, lijkt het erop dat alle eindcijfers en gemiddeldes de key `isPTA` met een waarde `false` hebben. Dit houdt in dat het cijfer geen onderdeel is van het Programma Toets en Afsluiting, wat ook logish is.

Nu is het zo dat ik in V6 zit, dit houdt in dat alle toetsen die ik dit jaar maak onderdeel zijn van het PTA, ik weet dus niet of eerdere jaren (<V5) bij normale cijfers alsnog `isPTA=true` hebben (ondanks dat ze feitelijk geen onderdeel zijn van het PTA, maar er staan wel meer dingen niet helemaal goed in Magister).

Verder blijft het dan ook de vraag of alle scholen dit consequent zo doen. Een methode waarbij we kolommen filteren gebaseerd op keywords zoals "eind" of "gemiddelde" lijkt me ook niet haalbaar wegens dezelfde reden.

**Comment by Argetan** [comment]
```
Kolomsoort: {
  0: "Onbekend"
  1: "Cijfers"
  2: "Gemiddelden"
  3: "Maxima"
  4: "Formule"
  5: "Minima"
  6: "Som"
  7: "Tel"
  8: "Cevo"
  9: "Tekst"
  10: "CevoKolCPE"
  11: "CevoKolCIE"
  12: "Weegfactor"
  13: "Eindcijfer"
  14: "TekortPunten"
}
```

Ik kwam dit stukje "documentatie" tegen. Wellicht dat dit kan worden gebruikt om te kijken met wat voor een soort cijfer we te maken hebben.
