### ISSUE TITLE
Authentication and security improvements

### ISSUE THREAD

**Issue by Argetan** [deltaproject/Delta#18]
```
(node:67643) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'Id' of undefined
    at retrieveAccount (/Users/julian/Delta/node_modules/magister.js/lib/magister.js:559:38)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:67643) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

Occasionally an error is thrown when authenticating, after refreshing a couple times it will go away. It should probably be looked into though.

**Comment by Argetan** [comment]
Ik ben er op het moment mee bezig dat wachtwoorden niet meer worden opgeslagen (in plain text). Zie [deze commit](https://github.com/Argetan/Delta/commit/eb0f846eb58a7da96ba9d97ea82a3a774f797801?diff=unified). Het idee is om wellicht the token op te slaan en die te gebruiken voor authenticatie (als je wilt dat je wordt onthouden). Ik weet echter niet of dat gaat lukken.

**Comment by keesvv** [comment]
Het is altijd het proberen waard! :smile: Als MagisterJS het inloggen en genereren van een token ondersteunt, dan zou dat geweldig zijn, omdat tokens niet snel kunnen worden gereversed naar het originele password.

**Comment by Argetan** [comment]
Ik ga kijken wat de conclusie van [deze issue](https://github.com/simplyGits/MagisterJS/issues/100) wordt. Mocht de token alleen maar voor korte tijd bruikbaar zijn kunnen we hem gebruiken voor logins kort na de eerste login.

In mijn branch heb ik het nu zo gedaan dat alleen je gebruikersnaam en wachtwoord worden opgeslagen. Het lijkt mij een kleine moeite als je bij iedere login je wachtwoord in moet voeren, zeker als dit de veiligheid verbeterd.

**Comment by lieuwex** [comment]
FWIW (geen idee of het uberhaupt van nut is) bij simplyHomework heb ik het vroeger zo gedaan dat hij eerst de laatste token probeerde, en als dat mislukte het opnieuw probeerde met een wachtwoord/gebruikersnaam combo. Maar dit was meer vanwege optimalisatie redenen dan beveiliging (inloggen kost toch weer wat requests, en simplyHomework heeft geen concept van ingelogd of niet, het werkte op een wat hoger niveau dan dat)
https://github.com/simplyGits/simplyHomework/blob/develop/packages/magister-binding/magister-binding.js#L190

**Comment by keesvv** [comment]
Hoi @Argetan ! Ik heb zojuist je `credentials-storage` branch bekeken, en het ziet er goed uit! Voor mijn gevoel lijkt de authenticatie zelfs iets soepeler te lopen. Ik ga hem mergen als je het goed vindt, en dan sluit ik deze issue!
