### ISSUE TITLE
Inloggen Windows 10 lukt niet

### ISSUE THREAD

**Issue by stephanlankhaar** [deltaproject/Delta#21]
Hallo, ik heb vandaag jullie project gevonden. Helaas kan ik niet inloggen op Windows 10 (zie screenshot), op Ubuntu 18.04 LTS lukt het wel. Ik heb beide geïnstalleerd via Node.js.

![electron_el42i4btmy](https://user-images.githubusercontent.com/38591947/51851662-a5dc8c00-2324-11e9-9dac-5dd929a57bc6.png)

Node.js versie: 11.8.0 (10.15.0 LTS werkte ook niet)
NPM versie: 6.5.0
Windows versie: 10 1809

**Comment by keesvv** [comment]
Hoi Stephan, wat cool dat je Project: Delta hebt gevonden! Ik heb toevallig ook een computer met Windows 10 build 1809, dus daar ga ik even naar kijken binnenkort. @Argetan en ik zijn ervan op de hoogte dat de achterliggende library Magister.js de laatste tijd wat problemen heeft met de authenticatie, dus dat zou een mogelijke oorzaak kunnen zijn.

P.S.: haha ik had niet verwacht dat Delta door 2 mensen in dezelfde week zou worden gevonden :smile:

**Comment by Argetan** [comment]
Hallo! Werkt mijn branch [credential-storage](https://github.com/Argetan/Delta/tree/credential-storage) wel voor je? Zo niet, zie je wellicht errors in de console?

**Comment by stephanlankhaar** [comment]
> Hallo! Werkt mijn branch [credential-storage](https://github.com/Argetan/Delta/tree/credential-storage) wel voor je? Zo niet, zie je wellicht errors in de console?

Jazeker hij doet het! Ontzettend bedankt.

**Comment by Argetan** [comment]
Deze issue kan worden gesloten @keesvv. 

_(Wellicht kan je mij permissie geven om issues te sluiten en labels toe te voegen?)_

**Comment by keesvv** [comment]
@Argetan Geen probleem! Ik zal je nu permissie geven 😄

**Comment by keesvv** [comment]
@Argetan Lukt het nu om labels toe te voegen?

**Comment by Argetan** [comment]
Nee, ik kan issues ook niet sluiten.

**Comment by keesvv** [comment]
> Nee, ik kan issues ook niet sluiten.

Als het goed is heb je een invite gekregen om Collaborator te worden, lukt het om die te accepteren?

**Comment by Argetan** [comment]
Ik heb geen mail binnen gekregen, maar het lijkt erop dat ik wel collaborator ben, alleen kan ik nog steeds geen labels weizigen of issues sluiten.

**Comment by keesvv** [comment]
@Argetan Kijk ik morgen wel even naar, nu moet ik nog wat dingen doen. Ik zoek wel even uit hoe dat GitHub permission systeem werkt 😉

**Comment by Argetan** [comment]
Is goed, als je iets van mij nodig hebt kan je me ook een email sturen jvdoorn@antarc.com, dat is wellicht handiger dan deze issue te spammen 😃
