### ISSUE TITLE
Inloggen mislukt

### ISSUE THREAD

**Issue by QkeleQ10** [deltaproject/Delta#44]
Wanneer ik inlog, krijg ik de foutmelding dat mijn gegevens onjuist zijn.

**Comment by keesvv** [comment]
Hi @QkeleQ10! Leuk dat je mijn project hebt gevonden en de moeite hebt genomen om een ticket te openen!
Dat is vervelend, als ik eraan toekom zal ik even ernaar kijken! Het zou namelijk kunnen zijn dat MagisterJS een nieuwe authcode heeft.
De laatste tijd ben ik niet meer actief bezig met Delta, maar ik zal het onderzoeken! 😁

**Comment by QkeleQ10** [comment]
Heel erg bedankt voor je razendsnelle reactie! Delta ziet er echt super geweldig uit. Het zou heel fijn zijn als ik eindelijk het slechte Magister kon opgeven en naar Delta kon.
________________________________

**Comment by keesvv** [comment]
Haha anytime! Dat is een groot compliment voor mij, dank je wel! 😄

**Comment by QkeleQ10** [comment]
Hou me alsjeblieft up-to-date als het probleem is gefixt of als ik op een andere manier kan inloggen

**Comment by keesvv** [comment]
@QkeleQ10 Natuurlijk, zal ik doen! Deze twee dagen waren heel hectisch voor mij, maar ik zal straks even kijken waar het probleem ligt. Ik laat je weten wanneer het gefixt is! 😁

**Comment by QkeleQ10** [comment]
Oké, heel erg bedankt!

**Comment by QkeleQ10** [comment]
Ik bedoelde niet het Issue te sluiten haha

**Comment by keesvv** [comment]
Heheh geen probleem hoor! 😉

**Comment by Netlob** [comment]
Ja MagisterJS heeft wat problemen. Sinds de nieuwe login van magister zijn er een aantal dingen veranderd. We zijn druk bezig het te verhelpen, maar het makkelijkste is om even terug te springen naar versie "^2.0.0-alpha.12" van MagisterJS (`npm i magisterjs@2.0.0-alpha.12`)

**Comment by QkeleQ10** [comment]
Bedoel je dat ik dat zelf moet doen? Of word dat nu behind the scenes gedaan? Ben zelf niet zo goed met npm enzo...
________________________________

**Comment by Netlob** [comment]
Nee. Dat zou de maker moeten doen en dan de app opnieuw distribueren :)

**Comment by QkeleQ10** [comment]
Oh ok

**Comment by keesvv** [comment]
@QkeleQ10 @Netlob Als ik zometeen thuis ben zal ik een PR maken met de fix 😄

**Comment by QkeleQ10** [comment]
Ik zag op de roadmap dat je plant om een nieuwe laad-animatie te maken. 
Ik heb een idee: ![ezgif-3-206811685cde](https://user-images.githubusercontent.com/55982900/66147413-14d65700-e60f-11e9-9067-1d70de3b1445.gif)
Of misschien langzamer:  ![ezgif-3-07abc2baaa30](https://user-images.githubusercontent.com/55982900/66147497-42bb9b80-e60f-11e9-909d-d01961b29b52.gif)
Ik kan hem ook nog langzamer doen

**Comment by Netlob** [comment]
Ziet er sick uit!

**Comment by keesvv** [comment]
@QkeleQ10 Haha, huh?! Ik heb die niet gemaakt even voor de duidelijkheid, maar hij ziet er echt super gaaf uit! :smile: Die kunnen we misschien binnenkort implementeren.

**Comment by keesvv** [comment]
@QkeleQ10 @Netlob Even een update:
Ik heb daarnet allerlei stappen genomen om het probleem te fixen, onder andere:
- Ik heb geüpgrade van MagisterJS `2.0.0-alpha.8` naar `2.0.0-alpha.12`
- Ik heb de nieuwste authcode gebruikt
- Ik heb `@magisterjs/dynamic-authcode` geïnstalleerd om te kijken of deze het probleem kon verhelpen
- Ik heb geprobeerd zonder het token-systeem te werken.

Helaas werkte geen van dit alles, en ik ben tot de conclusie gekomen dat het probleem dus bij MagisterJS/de Magister-API ligt. Hier kan ik zelf nu erg weinig aan veranderen, hopelijk kan ik binnenkort kijken of er een nieuwe authcode te halen valt. :grimacing:

**Comment by QkeleQ10** [comment]
> Heb jij deze gemaakt?!

Ja, dat heb ik zojuist gedaan! Als je ooit iets nodig hebt dat te maken heeft met graphic design, vraag het maar 😄

> Helaas werkte geen van dit alles,

Dat is jammer, er is dus geen manier om in te loggen op het moment?

**Comment by Netlob** [comment]
@keesvv oh vergeten te zeggen: magister heeft **weer**(...) een nieuw algoritme voor het genereren van de aiuthcode, de dynamic authcode parser werkt dus niet meer. Beste wat je kan doen is de authcode uit magister extracten. Denk aan een headless browser voor server apps, of (ik geloof dat dit react is) een request met een allow redirect erin.

Voorbeeld code: https://github.com/mamorgen/magbot3/blob/master/lib/magister/authcode.function.js
success haha :)

**Comment by keesvv** [comment]
Super bedankt voor de input, @Netlob! Hahah hebben ze het alweer veranderd? Heb je code eventjes bekeken, ik zie dat je Puppeteer gebruikt, daar heb ik wel eens van gehoord. Ik snap het systeem: een browser window wordt gesimuleerd die naar de magisterpagina van je school gaat, en dan wacht deze op een request naar de username challenge (de browser heeft dan toegang om deze te bereiken). Ik zal dit weekend kijken of het mij lukt! :smile:

Even een andere update over dit project: ik kan Delta niet meer erg actief maintainen aangezien ik bezig ben aan een heel groot closed-source project op dit moment. Ik blijf uiteraard actief met issues en pull requests, maar zodra ik het inlogprobleem heb opgelost zal ik niet meer veel tijd besteden aan het vrijwillig schrijven van nieuwe code. Je bent altijd welkom om bijdragen te leveren, pull requests te maken etc. en ik zal er zo snel mogelijk naar kijken! Maar in de toekomst wil ik min of meer kijken of ik een nieuwe maintainer voor dit project kan vinden.

**Comment by keesvv** [comment]
Even een update: ik ben nog niet toegekomen aan een fix maken, omdat ik het gigantisch druk met school had dit weekend, ik zal proberen om het ergens deze week te fixen. Je bent altijd van harte welkom om een pull request te maken!

**Comment by QkeleQ10** [comment]
Misschien kan @Netlob een pull request maken? 

> @keesvv oh vergeten te zeggen: magister heeft weer(...) een nieuw algoritme voor het genereren van de aiuthcode, de dynamic authcode parser werkt dus niet meer. Beste wat je kan doen is de authcode uit magister extracten. Denk aan een headless browser voor server apps, of (ik geloof dat dit react is) een request met een allow redirect erin.

Voorbeeld code: https://github.com/mamorgen/magbot3/blob/master/lib/magister/authcode.function.js
success haha :)

**Comment by QkeleQ10** [comment]
Nog enige updates? Ik ben heel enthousiast over Delta nu, het voelt als een grote opening waarop ik wacht 🎉😜😎

**Comment by Netlob** [comment]
Heb zo een tussenuurtje en heb m'n laptop bij me. Zal kijken wat ik kan betekenen🙃

**Comment by LevitatingBusinessMan** [comment]
Haha, zo zie ik het graag. De beste commits zijn altijd tijdens schooluren geschreven.

**Comment by Netlob** [comment]
![image](https://user-images.githubusercontent.com/33723199/67074454-6c390300-f189-11e9-8a28-27f51d701f03.png)
haha wat is dit nou. "hoogste cijfer een 100,  gemiddelde een 194"

**Comment by QkeleQ10** [comment]
Hahahaha lol

**Comment by keesvv** [comment]
Hoi allemaal, ik had het deze twee weken echt onwijs druk met school en ik ben niet toegekomen aan een fix. Sorry als ik mensen zo lang heb laten wachten, ik heb inmiddels super veel dingen naast Delta te doen en het lukt mij niet meer om alle projecten en alles actief te houden. 🥴
@Netlob het ziet eruit alsof het is gelukt om in te loggen!! Echt geweldig, hoe heb je het uiteindelijk gefixt? 😁

**Comment by keesvv** [comment]
Ook even een quick note over de code: ik heb Delta geschreven toen ik nog maar net was begonnen met web development. Dus de code is echt een puinhoop geworden en als ik eerlijk ben snap ik er zelf ook helemaal niets meer van. 😝

Een tijd geleden is er een `rewrite`-branch gemaakt door @jvdoorn, waar hij Delta helemaal opnieuw heeft geschreven met een veel nettere codebase. Eventueel zouden we deze kunnen afmaken en vervolgens mergen, waardoor Delta iets meer maintainable wordt.

**Comment by QkeleQ10** [comment]
Ik kan helaas nog steeds niet inloggen. Moet ik Delta verwijderen en weer installeren?

@Netlob op Studeo waren jouw cijfers ook raar aangegeven. Ligt dat misschien aan je school? Ik had daar geen problemen mee namelijk.

**Comment by LevitatingBusinessMan** [comment]
Het is me in t verleden gelukt om de authcode met een request te krijgen, en volgensmij heeft MagisterJS daar nu een aparte repo voor.

**Comment by keesvv** [comment]
@Netlob Top, super bedankt voor de info!! 😄 Heel nice dat het gelukt is om een updated authcode te vinden. Ik wist dat er wat problemen waren met de authcode, maar ik vond het zelf heel overkill om Puppeteer te installeren (zoals je al zegt: het is een super grote dependency).

Een hele server hosten die de authcodes dynamisch ophaalt lijkt mij al helemaal overkill, vooral voor een open source project, aangezien daar ook kosten aan verbonden zijn (ik heb zelf een server maar die is niet public). 😅

Misschien komt er ooit nog een library uit die dit nog makkelijker kan handelen, maar voor nu zouden we het misschien op deze manier moeten doen. In ieder geval, super tof dat je de tijd ervoor hebt genomen en als je wil kun je een PR maken zodat ik een nieuwe release kan maken met de nieuwe (waarschijnlijk tijdelijke) authcode.

**Comment by keesvv** [comment]
@LevitatingBusinessMan Klopt, die heb ik ook al geprobeerd. Daar zijn twee packages voor, en beiden werken ze niet meer met het nieuwe inlogsysteem 😬

**Comment by keesvv** [comment]
Oeps, dat ging verkeerd, sorry! 😅

**Comment by Netlob** [comment]
Ja klopt die repos zijn verouderd. Ik heb nog een servertje draaien waar ik evt nog t op kan draaien.

**Comment by LevitatingBusinessMan** [comment]
Misschien moet je dan even een issue maken, dan is het waarschijnlijk zo gefixt. MagisterJS is ook afhankelijk van die package.

**Comment by LevitatingBusinessMan** [comment]
Ik zou zelf er naar kijken, maar ik zit bij een open dag. Misschien moeten we ook even de aandacht van @idiidk erbij halen

**Comment by idiidk** [comment]
Yo, what's up? Dit is wel een lange thread moet ik zeggen :D

**Comment by QkeleQ10** [comment]
Het enige wat ik weet is dat er iets mis is met de authcode van Delta

**Comment by LevitatingBusinessMan** [comment]
Van wat ik ervan begrepen heb, authcode kapoet.

**Comment by idiidk** [comment]
Oke dit kan best kloppen, ik weet dat er een fout in m'n magister-auth package zit waardoor die de authcode niet van Magister pakt. Was al bezig met een update, denk dat ik vanmiddag wel ff een pull request kan maken

**Comment by Netlob** [comment]
was vergeten de PR aan te maken, dus heb dat net even gedaan. (https://github.com/deltaproject/Delta/pull/45)

delta werkt weer 🎉 

notes:
`Little hotfix using my own server. The authcode at http://78.47.72.123/code.json is updated every minute, which should be fine right now.`

**Comment by keesvv** [comment]
Hi @Netlob, echt super bedankt voor je PR!! Geweldig dat je de tijd hebt willen nemen om Delta weer aan de praat te krijgen, echt top! :smile: :tada: 
Ik zal hem gelijk mergen, en dan release ik de nieuwe versie! :+1: :smile:

**Comment by keesvv** [comment]
Ik heb een nieuwe release aangemaakt voor Delta! Deze kun je [hier vinden](https://github.com/deltaproject/Delta/releases/tag/v0.6.6-stable).
Super bedankt allemaal voor de support en bijdragen, appreciate it 😁

**Comment by Netlob** [comment]
![image](https://user-images.githubusercontent.com/33723199/67626063-aa4bbc00-f846-11e9-8f15-6f297cf87361.png)

**Comment by keesvv** [comment]
Hmm, dat is apart. Lijkt er bijna op alsof de `node_modules` niet mee zijn gekomen in de release. Zal er straks wel even naar kijken!

**Comment by keesvv** [comment]
Probleem is opgelost! Bleek dat alleen `dependencies` waren meegenomen, zonder `devDependencies`. Dit hoort natuurlijk niet zo te werken, maar nu heb ik Delta gepackaged wél met de `devDependencies`. [Hier is de nieuwe release](https://github.com/deltaproject/Delta/releases/tag/v0.6.7-stable) :smile:

**Comment by QkeleQ10** [comment]
![image](https://user-images.githubusercontent.com/55982900/67659642-1ddfed00-f95d-11e9-9327-0f73e296ee24.png)

**Comment by QkeleQ10** [comment]
Zelfde fout als Netlob had?

**Comment by keesvv** [comment]
Oké, het lijkt erop alsof het dan alleen voor Linux gefixt is (heb het niet getest op Windows). Dan ga ik straks kijken of het probleem ligt bij `electron-packager`, dat zal het probleem dan moeten zijn 😬

**Comment by QkeleQ10** [comment]
Ok thanks!

**Comment by keesvv** [comment]
Het zou als het goed is nu opgelost moeten zijn! Ik heb het nu getest op Windows en Linux, en beiden werken helemaal perfect! Zelf heb ik geen Mac/MacBook, dus voor de Apple gebruikers: ik kan het helaas zelf niet testen. Het bleek uiteindelijk dat `electron` een `devDependency` was en niet een normale `dependency`, waardoor Delta niet in zijn geheel geïnstalleerd werd. [Hopelijk werkt deze release wel](https://github.com/deltaproject/Delta/releases/tag/v0.6.8-stable)! 😄

**Comment by NoahvdAa** [comment]
> Het zou als het goed is nu opgelost moeten zijn! Ik heb het nu getest op Windows en Linux, en beiden werken helemaal perfect! Zelf heb ik geen Mac/MacBook, dus voor de Apple gebruikers: ik kan het helaas zelf niet testen. Het bleek uiteindelijk dat `electron` een `devDependency` was en niet een normale `dependency`, waardoor Delta niet in zijn geheel geïnstalleerd werd. [Hopelijk werkt deze release wel](https://github.com/deltaproject/Delta/releases/tag/v0.6.8-stable)! 😄

Ik kan bevestigen dat Delta nu werkt op Mac.

**Comment by keesvv** [comment]
Perfect, bedankt voor de bevestiging @NoahvdAa! 😁

**Comment by NoahvdAa** [comment]
Ik kan nu weer niet inloggen, maar dat lijkt eraan te liggen dat @Netlob 's server geen authcode teruggeeft.

**Comment by NoahvdAa** [comment]
Ik kan soms niet inloggen en dat lijkt eraan te liggen dat bij mij @Netlob 's server soms geen authcode teruggeeft.

**Comment by Netlob** [comment]
Klopt. Heb gister grote problemen gehad met m'n server waardoor oa de
database van magbot was verwijderd... Heb daarom het een en ander moest
omgooien op de server omdat dat even de prioriteit had. Ik zal vanmiddag
alles weer goed zetten voor deaurhcode. Sorry voor t ongemak...

**Comment by QkeleQ10** [comment]
Geen prioriteit hoor, maar ben gewoon benieuwd naar de status van de laadanimatie. Zou super gaaf zijn als dat geïmplementeerd zou kunnen worden, toch?

**Comment by QkeleQ10** [comment]
![image](https://user-images.githubusercontent.com/55982900/67844875-cbd6cd00-fafe-11e9-9aee-d0accf2f3cf6.png)

**Comment by keesvv** [comment]
@QkeleQ10 Het lijkt erop dat de authcode-server van @Netlob tijdelijk niet goed functioneert, dus dat kan de oorzaak van het probleem zijn.

Over de laadanimatie: ik vind het een super goed idee om het te implementeren, alleen ben ik zelf de komende tijd heel erg druk met allerlei dingen, en ik kan niet actief aan Delta werken, dus misschien is er iemand anders bereid om deze te implementeren (of ik, misschien, zodra ik wat meer tijd heb). Het is wel een super leuk idee! 😁

**Comment by QkeleQ10** [comment]
Ik weet echt niet of dit haalbaar is, maar misschien is het een idee om @Netlob's Magiscore te combineren met Delta. Op dit moment werken ze allebei om een andere reden niet, dus als de krachten gecombineerd worden zou het wel eens geweldig kunnen zijn!

**Comment by NoahvdAa** [comment]
> Op dit moment werken ze allebei om een andere reden niet, dus als de krachten gecombineerd worden zou het wel eens geweldig kunnen zijn!

Dit komt doordat @Netlob's server offline is, en daardoor kan Delta hem niet bereiken. Ik kan wel zelf even een tijdelijke vervangende server regelen, totdat die van @Netlob weer online is.

**Comment by NoahvdAa** [comment]
> > Op dit moment werken ze allebei om een andere reden niet, dus als de krachten gecombineerd worden zou het wel eens geweldig kunnen zijn!
> 
> Dit komt doordat @Netlob's server offline is, en daardoor kan Delta hem niet bereiken. Ik kan wel zelf even een tijdelijke vervangende server regelen, totdat die van @Netlob weer online is.

PR #46 veranderd de authcode-server naar mijn server, zodat Delta het kan blijven doen terwijl @Netlob's server offline is.

**Comment by Netlob** [comment]
> Ik weet echt niet of dit haalbaar is, maar misschien is het een idee om @Netlob's Magiscore te combineren met @keesvv's Delta. Op dit moment werken ze allebei om een andere reden niet, dus als de krachten gecombineerd worden zou het wel eens geweldig kunnen zijn!

De webversie van magiscore is eigenlijk niet bestaant. Dat was een manier om voordat het de app was het te kunnen openen op je telefoon. Wil je magiscore gebruiken zul je dus even je telefoon moeten pakken. Al kan ik wel kijken of ik magiscore weer aan de praat krijg.

Als dev kijkent gaat dat heel lastig worden ipv met de 2 compleet verschillende frameworks die gebruikt worden haha.

**Comment by keesvv** [comment]
Super bedankt @NoahvdAa voor jouw PR en de moeite om het op je eigen server te zetten voor tijdelijk! Heb hem gemerged, ik zal elk moment een release maken! :smile: :+1:

**Comment by QkeleQ10** [comment]
> De webversie ... worden haha.
Oh dat had ik me niet gerealiseerd 😄

> ik zal elk moment een release maken! 
🎈🎉

**Comment by keesvv** [comment]
Ik heb de release gemaakt, [je kunt hem hier vinden](https://github.com/deltaproject/Delta/releases/tag/v0.6.9-stable)! :smile:

**Comment by Netlob** [comment]
@keesvv we hebben trouwens een discordserver met alle magisterapps etc bij elkaar (magistat, studeo, magiscore etc) maar ook magisterjs en een delta channel erin.
https://discordapp.com/invite/rhWWrAw :)

**Comment by QkeleQ10** [comment]
Oh trouwens, Delta werkt! (Op dat met de cijfers en agenda na)
