### ISSUE TITLE
Data onjuist

### ISSUE THREAD

**Issue by QkeleQ10** [deltaproject/Delta#52]
![image](https://user-images.githubusercontent.com/55982900/68104738-88a0a380-fedc-11e9-88ed-d0e4f994a555.png)
Ik heb 1 onvoldoende gehad dit jaar, dat was een 5,1

**Comment by QkeleQ10** [comment]
![image](https://user-images.githubusercontent.com/55982900/68105040-90ad1300-fedd-11e9-9c26-8688f7467cf4.png)
En hij toont niet de agenda van vandaag...

**Comment by QkeleQ10** [comment]
Ik ben echt een zeurpiet hè?

**Comment by jvdoorn** [comment]
> ![image](https://user-images.githubusercontent.com/55982900/68104738-88a0a380-fedc-11e9-88ed-d0e4f994a555.png)
> Ik heb 1 onvoldoende gehad dit jaar, dat was een 5,1

Hoe zit het met gemiddelden? Ik herinner me vaag dat we namelijk naar alle cijfers kijken (en dus ook gemiddelden etc.) mogelijk gaat het daar ergens fout.



> ![image](https://user-images.githubusercontent.com/55982900/68105040-90ad1300-fedd-11e9-9c26-8688f7467cf4.png)
> En hij toont niet de agenda van vandaag...

Die is interessant.. ben je toevallig vrij op maandag?

**Comment by jvdoorn** [comment]
Als je wil zou je zelf de rewrite branch kunnen runnen om te kijken of die werkt, mogelijk dat dan eerst de nieuwe updates in de master branch moeten worden gemerged.

**Comment by keesvv** [comment]
@QkeleQ10 Over de agenda: dat was eigenlijk als intended feature bedoeld, omdat je dan op de dag zelf de agenda van morgen kunt bekijken. 😅 Kan altijd nog veranderd worden.

Over de gemiddelden en onvoldoendes: dat zou ik echt niet weten hoe dat kan, misschien zou je inderdaad de `rewrite` branch kunnen checken 😉

**Comment by QkeleQ10** [comment]
> Hoe zit het met gemiddelden? Ik herinner me vaag dat we namelijk naar alle cijfers kijken (en dus ook gemiddelden etc.) mogelijk gaat het daar ergens fout.

Geen idee, volgensmij werken die wel oké. Niet helemaal zeker though.


> Die is interessant.. ben je toevallig vrij op maandag?

Nope


> Over de agenda: dat was eigenlijk als intended feature bedoeld, omdat je dan op de dag zelf de agenda van morgen kunt bekijken.

@keesvv Misschien is het handig om dat alleen te doen als je al je afspraken van vandaag afgerond hebt.


> Over de gemiddelden en onvoldoendes: dat zou ik echt niet weten hoe dat kan, misschien zou je inderdaad de rewrite branch kunnen checken 😉

Geen verstand van haha

**Comment by QkeleQ10** [comment]
![image](https://user-images.githubusercontent.com/55982900/68113092-3a4acf00-fef3-11e9-9bbf-7d884e583bf3.png)
Dit lijkt ook opeens niet meer te werken lol
