### ISSUE TITLE
Inloggen niet mogelijk

### ISSUE THREAD

**Issue by Argetan** [deltaproject/Delta#7]
Recent is the authenticatiecode van `Magister.js` [veranderd](https://github.com/simplyGits/MagisterJS/issues/108). Hierdoor is het niet meer mogelijk om in te loggen.

**Comment by keesvv** [comment]
Ah kijk, dan begrijp ik wat er aan de hand is! Iemand uit mijn klas vertelde mij ook al dat het inloggen vastliep bij het laadscherm, dus ik ga vanmiddag kijken of ik de `authCode` kan patchen.

**Comment by Argetan** [comment]
Het probleem kan worden verholpen door te updaten naar de nieuwste versie van `Magister.js` (zie #8). Deze versie van `Magister.js` maakt gebruik van een NPM package om de authenticatiecode op te halen. Dit houdt echter in dat iedere keer dat de code veranderd die package zou moeten worden geupdate. Een alternatief is om de code op te halen van de GitHub pagina waar hij wordt gehost. Zie deze [pagina](https://github.com/simplyGits/magisterjs-authcode).

**Comment by keesvv** [comment]
Oh ik begrijp het. Het lijkt mij inderdaad handig om deze dynamisch op te halen, dus dat ga ik straks gelijk implementeren! Anders, feel free om bij te dragen, het is immers open source 😄

**Comment by keesvv** [comment]
Ik heb de issue opnieuw geopend aangezien het probleem nog niet is verholpen. Ik zal binnenkort zo snel mogelijk een Release maken die deze problemen patcht 👍🏻

**Comment by keesvv** [comment]
Ik heb er even naar gekeken, en na de update schijnt het inloggen en de dropdown weer te werken. Het zou kunnen zijn dat het alleen werkt op mijn systeem, maar ik heb geen aanpassingen gedaan verder zoals het ophalen van een authCode. Zie screenshots:

![auth](https://user-images.githubusercontent.com/22598668/51426288-b97f4880-1be8-11e9-9675-4de5d1231f48.png)
![main](https://user-images.githubusercontent.com/22598668/51426290-bbe1a280-1be8-11e9-8530-3cc621b1e97d.png)

**Comment by Argetan** [comment]
Ik denk dat ik wellicht het probleem heb gevonden. Bij mij staat in de `style` van de datalist `display: none`. Welke waarde heeft deze bij jou?

![screen shot 2019-01-19 at 15 06 29](https://user-images.githubusercontent.com/19390615/51427877-fbb28500-1bfc-11e9-9982-245dc5ab31bb.png)

**Comment by keesvv** [comment]
Mmh, vreemd. Bij mij staat er ook `display: none` en dat het een `user agent stylesheet` is. Ik denk dat het probleem niet hier vandaan komt, want de reden waarom hier `display: none` aan wordt toegewijd is omdat `datalist`s niet weergegeven moeten worden, het is volgens mij echter een element dat wordt gerenderd door je browser maar wat niet zichtbaar is in DevTools. Ik denk dat het per OS verschilt, misschien worden dropdowns niet goed behandeld in macOS.

**Comment by keesvv** [comment]
Hoewel bij mij ook `display: none` staat wordt de `datalist` alsnog weergegeven dus dat is het aparte.
